version: 2.1

orbs:
  node: circleci/node@4.4.0
  codecov: codecov/codecov@1.2.3

jobs:
  tests:
    docker:
      - image: circleci/node:14.17.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint check
          command: yarn lint
      - run: yarn cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node:14.17.0-browsers
      steps:
       - checkout
       - run:
            name: Check package version
            command: node scripts/check-version Hermogenes00 autoescola-nardini

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters: 
            branches:
              ignore: master
            tags:
              ignore: /.*/

